[package]
name = "progpow_gpu"
version = "0.1.0"
authors = ["Brick Abode <a@a.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.51"
bigint = "4.4.1"

[build-dependencies]
bindgen = "0.71.1"
cmake = "0.1.50"
filetime = "0.2"

[features]
default = []
cuda = []
opencl = []



